// מיפוי תוכן קוד QR -> מספר כיסא (1-14). נוצר ע"י generate-qr.
window.SEAT_CODES = {
  "CINEMA-SEAT:LQ7E6T": 1,
  "CINEMA-SEAT:76ECSW": 2,
  "CINEMA-SEAT:5UGDR3": 3,
  "CINEMA-SEAT:U2QDBD": 4,
  "CINEMA-SEAT:LNHJJX": 5,
  "CINEMA-SEAT:UTMLLZ": 6,
  "CINEMA-SEAT:TBVSHC": 7,
  "CINEMA-SEAT:SE3U3A": 8,
  "CINEMA-SEAT:R3EP82": 9,
  "CINEMA-SEAT:8XRNL4": 10,
  "CINEMA-SEAT:2RYAGF": 11,
  "CINEMA-SEAT:G3JPX9": 12,
  "CINEMA-SEAT:GAWS7S": 13,
  "CINEMA-SEAT:9BM23C": 14
};
